<a href="https://colab.research.google.com/github/bosunKwak/BigData/blob/main/tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Simple CPU/GPU Example

In [4]:
import torch

x = torch.tensor([[1,2,3],[4,5,6]])
y = torch.tensor([[7,8,9],[10,11,12]])
z = x+y
# 더할때는 차원이 같아야함

print(z)
# tensor([[ 8, 10, 12],
#         [14, 16, 18]])
print(z.size())
# torch.Size([2, 3])

tensor([[ 8, 10, 12],
        [14, 16, 18]])
torch.Size([2, 3])


In [1]:
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"
x = torch.tensor([[1,2,3],[4,5,6]], device = device)
y = torch.tensor([[7,8,9],[10,11,12]], device = device)
z = x+y

print(z)
# tensor([[ 8, 10, 12],
#         [14, 16, 18]])
print(z.size())
# torch.Size([2, 3])
print(z.device)
# CPU 환경 : cpu 출력
# GPU 환경 : 

tensor([[ 8, 10, 12],
        [14, 16, 18]], device='cuda:0')
torch.Size([2, 3])
cuda:0


# Moving Tensors Between CPUs and GPUs

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"
x = x.to(device)
y = y.to(device)
z = x+y
z = z.to("cpu")

print(z)
print(z.size())
print(z.device)

tensor([[ 8, 10, 12],
        [14, 16, 18]])
torch.Size([2, 3])
cpu


# Creating Tensors

In [4]:
import numpy

# Created from pre-existing arryas
w = torch.tensor([1,2,3]) # From a list
print(w)
w = torch.tensor((1,2,3)) # From a tuple
print(w)
w = torch.tensor(numpy.array([1,2,3])) # From a NumPy array
print(w)

# Initialized by size
w = torch.empty(100,200) # Uninitialized
print(w)
w = torch.zeros(100,200) # All elements initialized with 0.0
print(w)
w = torch.ones(100,200) # All elements initialized with 1.0
print(w)

tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([[-1.9380e-17,  3.0715e-41,  5.7397e-42,  ...,         nan,
          7.2293e-37,         nan],
        [ 6.1090e-34,  2.3040e-36,  3.5412e-37,  ...,  9.0278e-35,
                 nan,  6.2081e-38],
        [ 1.4326e-38,  1.7633e-38,  7.1927e-34,  ...,  7.5242e-36,
          1.7454e-34,  1.7756e-34],
        ...,
        [ 7.4473e-40,  1.7488e-42,  5.3586e-42,  ...,  1.1020e-39,
          1.6473e-39,  1.1103e-39],
        [ 0.0000e+00,  7.3469e-40,  1.6473e-39,  ...,  2.1412e-42,
          2.3430e-42,  2.5672e-42],
        [ 2.9147e-42,  3.1165e-42,  3.3071e-42,  ...,  1.5919e-42,
          1.6031e-42,  1.6255e-42]])
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,

## Random 하게 만드는 방법

### 1. Initialized by size with random values

In [5]:
w = torch.rand(100,200) # From a uniform distribution on the interval[0,1]
print(w)
w = torch.randn(100,200) # From a normal distribution(mean = 0, variance=1)
print(w)
w = torch.randint(5,10,(100,200)) #Random integer between 5 and 10
print(w)

tensor([[0.9343, 0.1731, 0.7107,  ..., 0.0439, 0.1085, 0.2669],
        [0.2547, 0.3280, 0.5041,  ..., 0.9993, 0.7357, 0.8573],
        [0.2046, 0.1942, 0.4954,  ..., 0.1933, 0.3430, 0.6789],
        ...,
        [0.2160, 0.1510, 0.6325,  ..., 0.5057, 0.2622, 0.6129],
        [0.9525, 0.9305, 0.1362,  ..., 0.7900, 0.6940, 0.2256],
        [0.1485, 0.4753, 0.3492,  ..., 0.7329, 0.4615, 0.1926]])
tensor([[-0.5567,  0.1274, -1.4172,  ...,  0.0668,  1.0390, -0.5681],
        [ 1.0545,  1.2075, -1.0458,  ..., -0.1685, -0.8832,  0.0947],
        [ 0.7096, -0.2058, -0.4848,  ...,  0.4136,  0.6625,  0.8333],
        ...,
        [-1.6109,  0.4153, -1.8152,  ...,  1.1100,  1.8253,  0.8960],
        [-0.5086, -0.9900,  1.3358,  ...,  0.4703, -0.5274,  1.0229],
        [-0.6383,  1.1349, -0.5477,  ..., -1.3295,  0.2669,  0.0956]])
tensor([[6, 9, 7,  ..., 7, 8, 5],
        [8, 5, 9,  ..., 7, 9, 8],
        [7, 5, 8,  ..., 8, 8, 5],
        ...,
        [8, 6, 7,  ..., 7, 8, 6],
        [6, 9, 9,  

### 2. Initialized with specified data type or device

In [6]:
w = torch.empty((100,200),dtype = torch.float64,device="cuda")
print(w)

tensor([[3.9525e-323, 4.9407e-323, 5.9288e-323,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]], device='cuda:0', dtype=torch.float64)


### 3. Initialized to have same size, data type, and device as another tensor

In [9]:
x = torch.empty_like(w)
print(w)
print(x)

tensor([[3.9525e-323, 4.9407e-323, 5.9288e-323,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]], device='cuda:0', dtype=torch.float64)
tensor([[3.9525e-323, 4.9407e-323, 5.9288e-323,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        ...,
        

# Data type

In [12]:
# Specify data type at creation using dtype
w = torch.tensor([1,2,3], dtype=torch.float32)

# Using casting method to cast to a new data type
w.int() # w remains a float32 after cast
w = w.int() # w changes to int32 after cast
# add vs add_ : _는 in-place operation으로 바로 반영해주는 것

# Use to() method to cast to a new type
w = w.to(torch.float64) 
w = w.to(dtype = torch.float64)

# Python automatically converts data types during operations
x = torch.tensor([1,2,3], dtype = torch.int32)
y = torch.tensor([1,2,3], dtype = torch.float32)
z = x + y
print(z.dtype)

torch.float32


# Tensor Operation

In [17]:
x = torch.tensor([[1,2],[3,4],[5,6],[7,8]])
print(x)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


## 1. Indexing

In [18]:
# Indexing, returns a tensor
print(x[1,1])

# Indexing, returns value as Python number
print(x[1,1].item())

tensor(4)
4


## 2. Slicing

In [19]:
#[start:end:step]
print(x[:2,1])

# Boolean indexing
print(x[x<5]) # 전체 값을 비교해야하는 단점

tensor([2, 4])
tensor([1, 2, 3, 4])


## 3. Transposing and reshaping

In [21]:
# Transpose array, x.t() or x.T can be used
# 4x2차원 -> 2x4차원
print(x.t())

#Changing shape, Usually view() is preferred over reshape()
print(x.view(4,2))

tensor([[1, 3, 5, 7],
        [2, 4, 6, 8]])
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


## 4. Combining

In [22]:
## stack
y = torch.stack((x, x))
print(y)

tensor([[[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]],

        [[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]]])


## 5. Splitting

In [23]:
## unbind
a,b = x.unbind(dim = 1)
print(a,b)

tensor([1, 3, 5, 7]) tensor([2, 4, 6, 8])
