<a href="https://colab.research.google.com/github/bosunKwak/BigData/blob/main/Tensor_Operation_for_Mathematics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor Operation for Mathematics
- pointwise operations
- reduction functions
- comparison calculations
- linear algebra operations

## 1.Pointwise operation
- 대응되는 위치에 있는 숫자끼리 연산

### (1) Basic Math
- add()
- div()
- mul()
- neg()
- reciprocal()

In [28]:
import torch

a = torch.randint(0,10,(2,2))
b = torch.randint(0,10,(2,2))

print(a)
print(b)

tensor([[4, 8],
        [2, 8]])
tensor([[1, 6],
        [2, 6]])


In [29]:
torch.add(a,b)

tensor([[ 5, 14],
        [ 4, 14]])

In [30]:
torch.div(a,b)
# inf 나오면 무한대

tensor([[4.0000, 1.3333],
        [1.0000, 1.3333]])

In [31]:
torch.mul(a,b)

tensor([[ 4, 48],
        [ 4, 48]])

In [32]:
# (-1)곱
torch.neg(a)

tensor([[-4, -8],
        [-2, -8]])

In [33]:
# 역수
torch.reciprocal(a)

tensor([[0.2500, 0.1250],
        [0.5000, 0.1250]])

### (2) Truncation
- ceil()
- floor()
- remainder()
- round()
- trunc()

In [34]:
a = torch.randn(1)
b = torch.randn(1)
print(a)
print(b)

tensor([-0.5361])
tensor([-0.9107])


In [35]:
# 올림
torch.ceil(a)

tensor([-0.])

In [36]:
# 가장 큰 정수
torch.floor(b)

tensor([-1.])

In [37]:
# 나머지
torch.remainder(a,1)

tensor([0.4639])

In [38]:
# 반올림
torch.round(a)

tensor([-1.])

In [39]:
# 소수점 버리기
torch.trunc(a)

tensor([-0.])

### (3) Trigonometry
- sin()
- cos()

In [40]:
# sin() cos()

### (4) Exponents and logarithms
- exp()
- log()
- log10()
- pow()
- sqrt()
- square()




In [41]:
# exp(), log(), log10(), square() : 제곱

In [42]:
a = torch.tensor(2)
b = torch.tensor(3)
print(a)
print(b)

tensor(2)
tensor(3)


In [43]:
pow(2,3) # 2^3

8

In [44]:
torch.sqrt(a) # root

tensor(1.4142)

### (5) Other
- abs()

In [45]:
# 절대값
torch.abs(a)

tensor(2)

## 2.Reduction functions
- argmax(): 가장 큰 위치 선택
- argmin() : 가장 작은 위치 선택
- sum()
- mean() : 평균(차원 지정 및 유지 가능)
- mode() : 가장 빈도가 많은 값
- median() : 중간값 (1,1,1,3,4,4,5 중 "3")
- std() : 표준편차
- var() : 분산

In [46]:
a = torch.randint(0,10,(1,3))
print(a)

tensor([[2, 5, 7]])


In [47]:
torch.argmax(a)

tensor(2)

In [48]:
torch.argmin(a)

tensor(0)

In [49]:
# mean() : 평균
a = torch.rand(3,2)
print(a)

tensor([[0.2454, 0.0690],
        [0.0619, 0.8534],
        [0.7789, 0.8214]])


In [50]:
torch.mean(a)

tensor(0.4717)

In [51]:
# 차원 지정
torch.mean(a,dim=0)

tensor([0.3621, 0.5813])

In [52]:
# 차원 유지
b = torch.mean(a, dim=1, keepdim = True)

b.shape

torch.Size([3, 1])

## 3.Comparison calculations
- can return a tensor full of Booleans based on each element's value 

### (1) Compare a tensor to other tensors
- eq() , == 
- ge() , >=
- gt() , >
- le() , <=
- lt() , <
- ne() , !=

In [64]:
a = torch.randint(0,9,(2,2))
b = torch.randint(0,9,(2,2))
print(a)
print(b)

tensor([[8, 8],
        [6, 4]])
tensor([[7, 2],
        [8, 4]])


In [65]:
a == b

tensor([[False, False],
        [False,  True]])

In [66]:
torch.eq(a,b)

tensor([[False, False],
        [False,  True]])

### (2) Test tensor status or conditions
- isinf() : infinite 여부 
- isnan() : nan 여부 
- isfinite() : finite 여부 
- isclose() : 특정 값에 가까운지 여부

In [71]:
c = torch.tensor([[1,float('inf')],[float('nan'),8]])
print(c)

tensor([[1., inf],
        [nan, 8.]])


In [72]:
torch.isinf(c)
# inf 있는 위치에 true

tensor([[False,  True],
        [False, False]])

In [73]:
torch.isnan(c)

tensor([[False, False],
        [ True, False]])

### (3) Return a single Boolean for the entire tensor
  - equal()
  - allclose() : 모든 값이 특정 범위에 있는지 

### (4) Find value(s) over the entire tensor or along a given dimension 
- max()
- min()
- topk() : 큰값 k개 
- sort()

In [76]:
d = torch.tensor(range(10))
print(d)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [79]:
torch.topk(d,3)

torch.return_types.topk(values=tensor([9, 8, 7]), indices=tensor([9, 8, 7]))

In [80]:
# 내림차순 정렬
torch.sort(d, descending = True)

torch.return_types.sort(values=tensor([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]), indices=tensor([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]))

## 4.Linear algebra
- Matrix operations
- matmul() : matrix 간의 곱
- det() 
- tril() : 대각행렬을 중심으로 위->0
- triu()

In [86]:
a = torch.randint(0,9,(2,2))
b = torch.randint(0,9,(2,2))
print(a)
print(b)

tensor([[7, 1],
        [6, 5]])
tensor([[6, 1],
        [3, 1]])


In [87]:
torch.matmul(a,b)

tensor([[45,  8],
        [51, 11]])

In [88]:
a = torch.randint(0,9,(4,4))
print(a)

tensor([[6, 1, 2, 0],
        [8, 4, 7, 8],
        [0, 5, 0, 1],
        [5, 5, 0, 1]])


In [89]:
torch.tril(a)

tensor([[6, 0, 0, 0],
        [8, 4, 0, 0],
        [0, 5, 0, 0],
        [5, 5, 0, 1]])

# Automatic Differntiation(Autograd)
- 미분

## Why use this?
- 오차를 줄여줄 때 weight 따라서 전달하는데, 이때 미분 필요
- 각각의 기울기: gradient -> 미분을 사용하여 학습

## Examples

### (1) f = sum(x^2) 

In [90]:
# f = sum(x^2)

x = torch.tensor([[1,2,3],[4,5,6]],
                 dtype = torch.float, requires_grad=True)
print(x)
# [[1., 2., 3.],
#  [4., 5., 6.]]

f = x.pow(2).sum() # sum(x^2)
print(f)

f.backward()
print(x.grad) # df/dx = 2x
#[ 2.,  4.,  6.],
#[ 8., 10., 12.]

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
tensor(91., grad_fn=<SumBackward0>)
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])


###  (2) Q = 3a^3 - b^2

In [91]:
# Q = 3a^3 - b^2
import torch

a = torch.tensor([2.,3.], requires_grad = True)
b = torch.tensor([6.,4.], requires_grad = True)

Q = 3*torch.pow(a,3) - torch.pow(b,2)

external_grad = torch.tensor([1.,1.])
# backward? 암묵적으로 스칼라로 바꿔줌 
Q.backward(gradient=external_grad) # 앞 코드와 다르게, 스칼라가 아닌 벡터이기 때문에 명시적으로 지정 

print(a.grad) # dQ/da = 9a^2
print(b.grad) # dQ/db = -2b

tensor([36., 81.])
tensor([-12.,  -8.])
