<a href="https://colab.research.google.com/github/bosunKwak/BigData/blob/main/tensor_Operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor Operation for Mathematics

## 1. Basic Math

In [7]:
import torch

a = torch.randint(0,10,(2,2))
b = torch.randint(0,10,(2,2))

print(a)
print(b)

tensor([[3, 9],
        [3, 6]])
tensor([[7, 8],
        [3, 8]])


In [8]:
torch.add(a,b)

tensor([[10, 17],
        [ 6, 14]])

In [11]:
torch.div(a,b)
# inf 나오면 무한대

tensor([[0.4286, 1.1250],
        [1.0000, 0.7500]])

In [12]:
torch.mul(a,b)

tensor([[21, 72],
        [ 9, 48]])

In [13]:
# (-1)곱
torch.neg(a)

tensor([[-3, -9],
        [-3, -6]])

In [15]:
# 역수
torch.reciprocal(a)

tensor([[0.3333, 0.1111],
        [0.3333, 0.1667]])

## 2. Truncation

In [30]:
a = torch.randn(1)
b = torch.randn(1)
print(a)
print(b)

tensor([1.2150])
tensor([1.7218])


In [33]:
# 올림
torch.ceil(a)

tensor([2.])

In [34]:
# 가장 큰 정수
torch.floor(b)

tensor([1.])

In [36]:
# 나머지
torch.remainder(a,1)

tensor([0.2150])

In [37]:
# 반올림
torch.round(a)

tensor([1.])

In [39]:
# 소수점 버리기
torch.trunc(a)

tensor([1.])

## 3. Trigonometry

In [ ]:
# sin() cos()

## 4. Exponents and logarithms

In [ ]:
# exp(), log(), log10(), square() : 제곱

In [40]:
a = torch.tensor(2)
b = torch.tensor(3)
print(a)
print(b)

tensor(2)
tensor(3)


In [41]:
pow(2,3) # 2^3

8

In [42]:
torch.sqrt(a) # root

tensor(1.4142)

## 5. Other

In [43]:
# 절대값
torch.abs(a)

tensor(2)